apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nicoRest.fullname" . }}-config
  labels:
    {{- include "nicoRest.labels" . | nindent 4 }}
  annotations:
    {{- include "nicoRest.provenanceAnnotations" . | nindent 4 }}
data:
  nico-rest.yaml: |
    idp:
      mode: {{ .Values.idp.mode | quote }}
      external:
{{ toYaml .Values.idp.external | indent 8 }}
      bundled:
        enabled: {{ or (eq .Values.idp.mode "bundled") .Values.idp.bundled.enabled }}
        issuerURL: {{ printf "http://%s-bundled-idp.%s.svc.cluster.local:%v" (include "nicoRest.fullname" .) .Release.Namespace (.Values.idp.bundled.service.port | default 8080) | quote }}
    temporal:
      endpoint: {{ .Values.temporal.endpoint | quote }}
      namespace: {{ .Values.temporal.namespace | quote }}
    site:
      uuid: {{ .Values.site.uuid | quote }}
      name: {{ .Values.site.name | quote }}
    rest:
      publicURL: {{ .Values.rest.publicURL | quote }}
      corsAllowedOrigins:
{{ toYaml .Values.rest.corsAllowedOrigins | indent 8 }}
