version: 2
project_name: ubiquity
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/ubiquity/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/ubiquitycluster/ubiquity/cmd/ubiquity/cmd.Version={{ .Version }}
      - -X github.com/ubiquitycluster/ubiquity/cmd/ubiquity/cmd.Commit={{ .Commit }}
      - -X github.com/ubiquitycluster/ubiquity/cmd/ubiquity/cmd.Date={{ .Date }}
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"