FROM golang:1.26 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG VERSION=dev COMMIT=none DATE=unknown
RUN CGO_ENABLED=0 go build -ldflags "-X github.com/ubiquitycluster/ubiquity/cmd/ubiquity/cmd.Version=${VERSION} -X github.com/ubiquitycluster/ubiquity/cmd/ubiquity/cmd.Commit=${COMMIT} -X github.com/ubiquitycluster/ubiquity/cmd/ubiquity/cmd.Date=${DATE}" -o /ubiquity ./cmd/ubiquity/

FROM gcr.io/distroless/static-debian12
COPY --from=build /ubiquity /usr/local/bin/ubiquity
ENTRYPOINT ["/usr/local/bin/ubiquity"]