#!/bin/bash

# Copyright The Ubiquity Authors.
#
# Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License.
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/ubiquitycluster/ubiquity/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script to update all license headers from Functional Source License to Apache 2.0

# Function to update a single file
update_file() {
    local file="$1"
    echo "Updating $file"
    
    # Create a temporary file
    local temp_file=$(mktemp)
    
    # Replace the license text and URL in the file
    sed -e 's/Licensed under the Functional Source License, Version 1\.0, Apache 2\.0 Change License/Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License/g' \
        -e 's/https:\/\/github\.com\/logicalisuki\/ubiquity\/blob\/main\/LICENSE\.md/https:\/\/github.com\/ubiquitycluster\/ubiquity\/blob\/main\/LICENSE/g' \
        -e 's/It also allows for the transition of this software to an Apache 2\.0 Licence/This software was previously licensed under the Functional Source License but has now transitioned to an Apache 2.0 License/g' \
        -e 's/on the second anniversary of the date we make the software available\./as of June 2025./g' \
        "$file" > "$temp_file"
    
    # Replace the original file with the updated content
    mv "$temp_file" "$file"
}

# Read the list of files and update each one
while IFS= read -r file; do
    if [[ -f "$file" ]]; then
        update_file "$file"
    fi
done << 'EOF'
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/prep.sh
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/clean-output.sh
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/build-images.sh
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/elements/ansible-awx-callback/package-installs.yaml
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/custom-elements/mofed/package-installs.yaml
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/custom-elements/gpfs/package-installs.yaml
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/custom-elements/ubiquity/package-installs.yaml
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/custom-elements/lustre/package-installs.yaml
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/mkimage/custom-elements/cloud-init-install/package-installs.yaml
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/scripts/delete-host.sh
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/scripts/cp-disk-image.sh
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/scripts/create-nodelist.sh
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/scripts/lib/networkData.sh
/Users/ccoates/Documents/git/ubiquity-open/tools/disk-image/scripts/reinstall_host.sh
/Users/ccoates/Documents/git/ubiquity-open/mkdocs.yml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/Makefile
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/argocd/defaults.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/argocd/argocd-cm.kustomize-buildoptions.patch.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/argocd/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/argocd/argocd-repo-tls-cert.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/argocd/apply.sh
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/argocd/values-seed.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/argocd/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/root/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/root/apply.sh
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/root/templates/stack.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/root/values-seed.yaml
/Users/ccoates/Documents/git/ubiquity-open/bootstrap/root/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/test/external_test.go
/Users/ccoates/Documents/git/ubiquity-open/metal/boot.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/group_vars/metal.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/Makefile
/Users/ccoates/Documents/git/ubiquity-open/metal/clean.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/vars/RedHat.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/vars/Debian-bullseye.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/vars/Ubuntu.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/vars/Debian.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/vars/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/tasks/RedHat.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/tasks/Debian.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/tasks/systemd_timers.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/tasks/systemd_timers_remove.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/tasks/unattended-upgrades.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/tasks/reboot.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/defaults/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/automatic_upgrade/handlers/handlers.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/metallb_config/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/metallb_config/defaults/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/pxe_server/tasks/infiniband.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/pxe_server/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/pxe_server/files/docker-compose.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/wake/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/tasks/crontab.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/tasks/package_manager.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/tasks/minimize_access.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/tasks/mounts.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/tasks/kernel_hardening.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/tasks/kernel_modules.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/tasks/auditd.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/defaults/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/hardening/handlers/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/dev_fixes/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/vars/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/tasks/grub.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/tasks/optimise-ssds.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/tasks/tuned.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/tasks/pam-limits.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/tasks/sysctl.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/defaults/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/tune/handlers/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/demo/non-privileged-user-create.sh
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/demo/privileged-deploy.yaml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/demo/dangerous-pod-root-in-host-unprivileged-user.sh
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/demo/dangerous-pod-root-in-host.sh
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/demo/non-privileged-deploy.yaml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/demo/php-demo.yaml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/defaults/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/files/kubeless/kubeless-rbac-manifest.yaml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/files/policy/restricted-psp.yaml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s/files/policy/cluster-admin-role.yaml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/tasks/template.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/tasks/upgrade.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/tasks/helm_repository.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/tasks/pre_flight_check.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/tasks/delete.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/tasks/install.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/defaults/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/cilium/handlers/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s-clean/tasks/umount_with_children.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/roles/k3s-clean/tasks/main.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/k3d-dev.yaml
/Users/ccoates/Documents/git/ubiquity-open/metal/inventories/prod.yml
/Users/ccoates/Documents/git/ubiquity-open/metal/cluster.yml
/Users/ccoates/Documents/git/ubiquity-open/Makefile
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/misc/nfs/pv-nfs.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/misc/nfs/pvc-nfs.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/misc/longhorn/pv-longhorn.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/misc/longhorn/pvc-longhorn.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/misc/codes/infinite.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/openpbs/openpbs.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/slurm/nfs/pvc-nfs.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/slurm/lh/pvc-nfs.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/slurm/lh/pvc-lh.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/htcondor-worker-deployment.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/schedd/docker-entrypoint.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/central-manager/docker-entrypoint.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/collector/docker-entrypoint.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/controller/docker-entrypoint.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/controller/htcondor-pool.py
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/build.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/negotiator/docker-entrypoint.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/worker/docker-entrypoint.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/worker-v2/docker-entrypoint.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/images/generate-password/docker-entrypoint.sh
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/htcondor-central-manager-service.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/htcondor-schedd-deployment.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-worker-deployment.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-worker-configmap-job.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-schedd-deployment.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-collector-deployment.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-worker-configmap.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-pool-deployment-rbac.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-negotiator-deployment.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-collector-service.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-pool-deployment.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/v2/htcondor-clusterrolebinding.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/htcondor/htcondor-central-manager-deployment.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/hpc-ubiq/oar/oar.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/trow/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/trow/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-events/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-events/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/harbor/Chart.yml
/Users/ccoates/Documents/git/ubiquity-open/platform/harbor/templates/harbor-config-overwrite-secret.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/harbor/templates/harbor-secrets.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/harbor/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/awx/awx-platform.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/awx/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/gitea/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/gitea/files/config/config.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/gitea/files/config/main.go
/Users/ccoates/Documents/git/ubiquity-open/platform/gitea/templates/config-job.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/gitea/templates/admin-secret.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/gitea/templates/config-source.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/gitea/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/dex/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/dex/templates/secret.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/dex/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-workflows/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-workflows/files/deploy-application.yml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-workflows/files/ci-workflow.yml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-workflows/files/html-modifier.yml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-workflows/files/git-checkout-pr.yml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-workflows/files/container-build.yml
/Users/ccoates/Documents/git/ubiquity-open/platform/argo-workflows/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/openldap/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/external-secrets/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/external-secrets/templates/clustersecretstore.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/keycloak/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/keycloak/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/onyxia/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/onyxia/templates/logo.yml
/Users/ccoates/Documents/git/ubiquity-open/platform/onyxia/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/renovate/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/renovate/templates/secret.yaml
/Users/ccoates/Documents/git/ubiquity-open/platform/renovate/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/hack/markdownlint.sh
/Users/ccoates/Documents/git/ubiquity-open/hack/kind_with_registry.sh
/Users/ccoates/Documents/git/ubiquity-open/storage/Makefile
/Users/ccoates/Documents/git/ubiquity-open/storage/dragonfly-system/charts-config.yaml
/Users/ccoates/Documents/git/ubiquity-open/storage/dragonfly-system/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/storage/dragonfly-system/apply.sh
/Users/ccoates/Documents/git/ubiquity-open/system/monitoring-system/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/monitoring-system/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/monitoring-system/templates/tls-secret.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/monitoring-system/templates/dgcm-exporter.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/monitoring-system/templates/secret.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/operator-lifecycle-manager/templates/catalogsource.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/operator-lifecycle-manager/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/baremetal-operator-system/storage/pvc-longhorn.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/longhorn-system/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/longhorn-system/templates/longhorn-nfs-installation.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/longhorn-system/templates/servicemonitor.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/longhorn-system/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/descheduler/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/descheduler/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/mysql-operator/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/pebble/pebble/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/pebble/pebble/deploy.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/pebble/pebble/service.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/pebble/pebble/configmap.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/pebble/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/nvidia-network-operator/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cert-manager/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cert-manager/templates/clusterissuer-prod.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cert-manager/templates/pebbleissuer.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cert-manager/templates/clusterissuer-staging.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cert-manager/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/metallb-system/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/metallb-system/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cvmfs-csi/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cvmfs-csi/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/kured/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/kured/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cluster-deps/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/cluster-deps/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/coredns-autoscaler/coredns-autoscaler.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/falco/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/falco/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/k8up-operator/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/k8up-operator/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/k8up-operator/schedule.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/k8up-operator/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/ingress-nginx/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/ingress-nginx/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/vault/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/vault/files/generate-secrets/config.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/vault/files/generate-secrets/main.go
/Users/ccoates/Documents/git/ubiquity-open/system/vault/templates/pvc.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/vault/templates/generate-secrets-source.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/vault/templates/generate-secrets-job.yaml
/Users/ccoates/Documents/git/ubiquity-open/system/vault/templates/cr.yaml
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/Makefile
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/network-1.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/openstack.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/network-2.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/infrastructure.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/external/keystone.py
/Users/ccoates/Documents/git/ubiquity-open/cloud/openstack/external/keystone.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/ovh/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/ovh/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/ovh/Makefile
/Users/ccoates/Documents/git/ubiquity-open/cloud/ovh/network-1.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/ovh/network-2.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/ovh/ovh.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/ovh/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/ovh/infrastructure.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/Makefile
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/network.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/tfvars.yml
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/azure.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/scripts/azcli.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/scripts/azlogin.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/scripts/test.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/infrastructure.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/azure/local.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/Makefile
/Users/ccoates/Documents/git/ubiquity-open/cloud/utils/azure/vmsizes/vmsizes.py
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/gcp.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/Makefile
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/network.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/infrastructure.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/external/machine_type.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/external/test.py
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/external/machine_type.py
/Users/ccoates/Documents/git/ubiquity-open/cloud/gcp/install_cloudinit.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/design/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/design/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/design/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/cluster_config/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/cluster_config/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/cluster_config/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/cluster_config/terraform_data.yaml
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/cluster_config/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/instance_config/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/instance_config/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/instance_config/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/instance_config/ansible/inventory/prod.yaml
/Users/ccoates/Documents/git/ubiquity-open/cloud/common/instance_config/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/outputs.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/config/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/Makefile
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/network.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/aws.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/tfvars.yml
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/scripts/awscli.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/scripts/awsconfigure.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/scripts/prepareAnsible.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/aws/infrastructure.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/gcloud/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/gcloud/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/gcloud/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/txt/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/txt/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/acme/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/acme/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/record_generator/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/record_generator/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/record_generator/key2fp.sh
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/record_generator/key2fp.py
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/cloudflare/main.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/cloudflare/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/cloud/dns/cloudflare/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/scripts/docker-regcreds.sh
/Users/ccoates/Documents/git/ubiquity-open/scripts/get-docker.sh
/Users/ccoates/Documents/git/ubiquity-open/scripts/ssh-key-setup.sh
/Users/ccoates/Documents/git/ubiquity-open/scripts/bmo/storage/pvc-longhorn.yaml
/Users/ccoates/Documents/git/ubiquity-open/scripts/bmo/bmo-create.sh
/Users/ccoates/Documents/git/ubiquity-open/scripts/test.py
/Users/ccoates/Documents/git/ubiquity-open/scripts/find-bmhosts.sh
/Users/ccoates/Documents/git/ubiquity-open/scripts/bm.sh
/Users/ccoates/Documents/git/ubiquity-open/scripts/docker-perms.sh
/Users/ccoates/Documents/git/ubiquity-open/scripts/create-nat.sh
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/tekton-pipelines/ingress.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/tekton-pipelines/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/tekton-pipelines/serviceaccount.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/tekton-pipelines/clusterrolebinding.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/opensm/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/opensm/files/nic_operator_helm_ci_start.sh
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/opensm/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/vault/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/vault/files/generate-secrets/config.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/vault/files/generate-secrets/main.go
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/vault/templates/rbac.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/vault/templates/generate-secrets-source.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/vault/templates/generate-secrets-job.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/platform/vault/templates/cr.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/jupyterhub/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/jupyterhub/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/external-dns/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/external-dns/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/kube-bench/job.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/cloudflared/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/cloudflared/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/system-upgrade/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/system-upgrade/k3s/server.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/system-upgrade/k3s/agent.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/system/system-upgrade/k3s/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/apps/cloudcmd/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/apps/cloudcmd/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/apps/cloudcmd/auth.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/apps/cloudshell/tls.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/apps/cloudshell/ingress.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/apps/cloudshell/kustomization.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/apps/cloudshell/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/apps/cloudshell/secret.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/matrix/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/disabled/matrix/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/external/main.tf
/Users/ccoates/Documents/git/ubiquity-open/external/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/external/Makefile
/Users/ccoates/Documents/git/ubiquity-open/external/namespaces.yml
/Users/ccoates/Documents/git/ubiquity-open/external/tfvars.yml
/Users/ccoates/Documents/git/ubiquity-open/external/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/external/modules/cloudflare/main.tf
/Users/ccoates/Documents/git/ubiquity-open/external/modules/cloudflare/versions.tf
/Users/ccoates/Documents/git/ubiquity-open/external/modules/cloudflare/variables.tf
/Users/ccoates/Documents/git/ubiquity-open/monitoring/loki/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/monitoring/loki/templates/loki-dashboard.yaml
/Users/ccoates/Documents/git/ubiquity-open/monitoring/loki/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/monitoring/monitoring-system/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/monitoring/monitoring-system/templates/dgcm-exporter.yaml
/Users/ccoates/Documents/git/ubiquity-open/monitoring/monitoring-system/templates/secret.yaml
/Users/ccoates/Documents/git/ubiquity-open/monitoring/monitoring-system/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/apps/cloudcmd/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/apps/cloudcmd/values.yaml
/Users/ccoates/Documents/git/ubiquity-open/apps/hajimari/Chart.yaml
/Users/ccoates/Documents/git/ubiquity-open/apps/hajimari/values.yaml
EOF

echo "All license headers have been updated!"
