/*
Copyright © 2026 Ubiquity Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/ubiquitycluster/ubiquity/blob/main/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Bootstrap Ubiquity configuration",
	Long:  `Initialize Ubiquity configuration in ~/.ubiquity/. Creates skeleton config with default values.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		env, _ := cmd.Flags().GetString("env")

		home, _ := os.UserHomeDir()
		ubiquityDir := filepath.Join(home, ".ubiquity")
		if err := os.MkdirAll(ubiquityDir, 0755); err != nil {
			return fmt.Errorf("creating .ubiquity directory: %w", err)
		}

		// Write skeleton config
		configPath := filepath.Join(ubiquityDir, ".ubiquity.yaml")
		if _, err := os.Stat(configPath); os.IsNotExist(err) {
			skeleton := `# Ubiquity cluster configuration
# Generated by 'ubiquity init'. Edit this file or use 'ubiquity configure'.

# Deployment environment: sandbox, dev, or prod
env: ` + env + `

# Cluster domain for ingress and DNS
# domain: ubiquitycluster.uk

# Default timezone for cluster nodes
# timezone: Europe/London

# Text editor for configuration review
# editor: vi

# Ingress provider: nginx, traefik, haproxy, contour
# ingress_provider: nginx

# Operating system for nodes: Rocky, Ubuntu, Fedora
# os: Rocky

# Kubernetes version
# kubernetes_version: v1.33.1+k3s1
`
			if err := os.WriteFile(configPath, []byte(skeleton), 0644); err != nil {
				return fmt.Errorf("writing config: %w", err)
			}
			fmt.Printf("Created skeleton config: %s\n", configPath)
		} else {
			fmt.Printf("Config already exists: %s (not overwritten)\n", configPath)
		}

		// Write state.json placeholder
		statePath := filepath.Join(ubiquityDir, "state.json")
		if _, err := os.Stat(statePath); os.IsNotExist(err) {
			os.WriteFile(statePath, []byte("{}"), 0644)
		}

		fmt.Printf("Initialized Ubiquity configuration for environment: %s\n", env)
		fmt.Printf("Config directory: %s\n", ubiquityDir)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}