# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity-open-open/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# This software was previously licensed under the Functional Source License but has now transitioned to an Apache 2.0 License
# as of June 2025.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: container-build
  annotations:
    workflows.argoproj.io/description: >-
      Uses Kaniko to build a container image within Kubernetes.
    workflows.argoproj.io/maintainer: 'Logicalis UK'
    workflows.argoproj.io/maintainer_url: 'https://github.com/logicalisuki/ubiquity-open'
    workflows.argoproj.io/version: '>= 3.4.2'
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: container-build
          template: container-build

  - name: container-build
    container:
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command: ['sh', '-c']
      args:
      - echo "Retrieving git clone..." && cp -R /workdir/{{workflow.parameters.app_repo}} /container-build

        /kaniko/executor --dockerfile="/container-build/{{workflow.parameters.app_repo}}{{workflow.parameters.path}}/{{workflow.parameters.dockerfile}}" --destination={{workflow.parameters.container_image}}:{{workflow.parameters.container_tag}} --context="dir:///container-build/{{workflow.parameters.app_repo}}/{{workflow.parameters.path}}" --cache=true --use-new-run=true --reproducible=true --push-retry=3
      volumeMounts:
        - name: container-build
          mountPath: /container-build
        - name: workdir
          mountPath: /workdir
      resources:
        requests:
          memory: 1Gi
          cpu: 1
    #20 minutes
    activeDeadlineSeconds: 1200