# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity-open-open/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# This software was previously licensed under the Functional Source License but has now transitioned to an Apache 2.0 License
# as of June 2025.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: html-modifier
  annotations:
    workflows.argoproj.io/description: >-
      Performs a sed command to inject the current running Workflow name into a given file.
    workflows.argoproj.io/maintainer: Logicalis UKI
    workflows.argoproj.io/maintainer_url: https://github.com/logicalisuki/ubiquity-open
    workflows.argoproj.io/version: '>= 3.4.2'
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: html-modifier
            template: html-modifier

    - name: html-modifier
      container:
        image: ubuntu:latest
        command:
          - /bin/bash
          - -c
          - |
            cd /workdir/\{\{workflow.parameters.app_repo\}\}/CI

            if grep -q CHANGEMEPLEASE index.html; then
              cat index.html | sed -E 's/CHANGEMEPLEASE/\{\{workflow.name\}\} and it used longhorn for artifact passing./g' > tmp_index.html
              mv tmp_index.html index.html
            else
              echo "CHANGEMEPLEASE was not found in index.html. Exiting"
              exit 1
            fi

            cat index.html

        volumeMounts:
          - name: workdir
            mountPath: /workdir
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
      #20 minutes
      activeDeadlineSeconds: 1200
