# Copyright The Ubiquity Authors.
#
# Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/ubiquitycluster/ubiquity/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# This software was previously licensed under the Functional Source License but has now transitioned to an Apache 2.0 License
# as of June 2025.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Main Cilium tasks file
- name: "Cilium | Check if Helm command is installed locally"
  ansible.builtin.shell: hash helm
  delegate_to: "{{ cilium_delegate_to }}"
  run_once: true
  changed_when: false
  args:
    executable: "/bin/bash"

- name: "Cilium | Set default action to only render template via Helm"
  ansible.builtin.set_fact:
    deploy_action: "template"
  delegate_to: "{{ cilium_delegate_to }}"
  run_once: true

- name: "Cilium | Set action to install via Helm"
  ansible.builtin.set_fact:
    deploy_action: "install"
  delegate_to: "{{ cilium_delegate_to }}"
  run_once: true
  when:
    - action is defined
    - '"install" in action'

- name: "Cilium | Set action to upgrade via Helm"
  ansible.builtin.set_fact:
    deploy_action: "upgrade"
  delegate_to: "{{ cilium_delegate_to }}"
  run_once: true
  when:
    - action is defined
    - '"upgrade" in action'

- name: "Cilium | Set action to delete via Helm"
  ansible.builtin.set_fact:
    deploy_action: "delete"
  delegate_to: "{{ cilium_delegate_to }}"
  run_once: true
  when:
    - action is defined
    - '"delete" in action'

- name: "Cilium | Include tasks to execute requested action"
  ansible.builtin.include_tasks:
    file: "tasks/{{ deploy_action | lower }}.yml"