# Copyright The Ubiquity Authors.
#
# Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/ubiquitycluster/ubiquity/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# This software was previously licensed under the Functional Source License but has now transitioned to an Apache 2.0 License
# as of June 2025.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Hardening tasks - Crontab

# CIS 1.4.1
# STIG 020030
# STIG 020040
- name: "Hardening | Ensure AIDE is installed"
  ansible.builtin.package:
    name: '{{ aide_package }}'
    state: present

- name: "Hardening | Ensure cronie package is installed"
  ansible.builtin.package:
    name: cronie
    state: present
  when: ansible_os_family == "RedHat" 

- name: "Hardening | Ensure cron package is installed"
  ansible.builtin.package:
    name: cron
    state: present
  when: ansible_os_family == "Debian"

# CIS 5.1.1
- name: "Hardening | Ensure cron daemon is enabled"
  ansible.builtin.service:
    name: crond
    enabled: yes

# CIS 1.4.2
- name: "Hardening | Configure Periodic Execution of AIDE"
  ansible.builtin.cron:
    name: run AIDE check
    minute: "5"
    hour: "4"
    weekday: "0"
    user: root
    job: /usr/sbin/aide --check

# CIS 5.1.2
# CIS 5.1.3
# CIS 5.1.4
# CIS 5.1.5
# CIS 5.1.6
# CIS 5.1.7
- name: "Hardening | Find cron files and directories"
  ansible.builtin.find:
    paths:
      - /etc
    patterns:
      - cron.hourly
      - cron.daily
      - cron.weekly
      - cron.monthly
      - cron.d
      - crontab
      - anacrontab
    file_type: any
  register: cron_directories

# CIS 5.1.8
- name: "Hardening | Ensure permissions on cron files and directories are configured"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: og-rwx
  with_items: "{{ cron_directories.files }}"

...
