#!/bin/bash
# Copyright The Ubiquity Authors.
#
# Licensed under the Functional Source License, Version 1.0, Apache 2.0 Change License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/ubiquitycluster/ubiquity/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# It also allows for the transition of this software to an Apache 2.0 Licence
# on the second anniversary of the date we make the software available.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo "############################################################"
echo "# Copy GPFS ISO from HOST                                  #"
echo "############################################################"

if [ -n "${DIB_GPFS_FILE}" ]; then
    cp ${DIB_GPFS_FILE} ${TMP_MOUNT_PATH}/tmp/
else
    echo "ERROR: DIB_GPFS_FILE is not set."
fi

