---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check that the MetalLB namespace is defined in vars
      ansible.builtin.assert:
        that:
          - metallb_namespace is defined
          - metallb_namespace == "metallb-system"
        quiet: true

    - name: Check that metallb config vars are defined
      ansible.builtin.assert:
        that:
          - metallb_network is defined
          - metallb_subnet_cidr_prefix is defined
        quiet: true
