#!/bin/bash
# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Functional Source License, Version 1.0, Apache 2.0 Change License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity-open/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# It also allows for the transition of this software to an Apache 2.0 Licence
# on the second anniversary of the date we make the software available.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo "############################################################"
echo "#      Install Whamcloud Lustre with kernel support        #"
echo "############################################################"

dnf config-manager --set-enabled powertools

cat <<EOF > /etc/yum.repos.d/lustre.repo
[lustre-client]
name=lustre-client
baseurl=https://downloads.whamcloud.com/public/lustre/latest-2.12-release/el8/client
# exclude=*debuginfo*
enabled=1
gpgcheck=0
EOF

echo "############################################################"
echo "#      Lustre REPO                                         #"
echo "############################################################"
ls /etc/yum.repos.d

cat /etc/yum.repos.d/lustre.repo

dnf config-manager --set-enabled lustre-client

unset ARCH
CHROOT_KERNEL=$(rpm -q --queryformat "%{installtime} %{version}-%{release}.%{arch}\n" kernel | sort -nr | sed -n 1p | cut -d' ' -f2)
install-packages kernel-devel-${CHROOT_KERNEL}
install-packages kernel-headers-${CHROOT_KERNEL}
install-packages kernel-tools-${CHROOT_KERNEL}
install-packages kernel-tools-libs-${CHROOT_KERNEL}
install-packages kernel-tools-libs-devel-${CHROOT_KERNEL}
install-packages lustre-client lustre-client-dkms
export ARCH=amd64

cat <<EOF > /etc/modprobe.d/lustre.conf
options lnet networks="o2ib2(ib0)"
EOF

cat <<EOF > /etc/modules-load.d/lustre.conf
lustre
EOF