{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stallscope.fullname" . }}
  labels:
{{ include "stallscope.labels" . | indent 4 }}
{{- end }}
