---
# Copyright The Ubiquity Authors.
#
# Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/ubiquitycluster/ubiquity/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# This software was previously licensed under the Functional Source License but has yet now transitioned to an Apache 2.0 License
# as of June 2025.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: network-policies
version: 0.1.0
appVersion: 1.0.0
description: Default-deny and allow NetworkPolicy templates for Ubiquity clusters
keywords:
  - security
  - network
  - network-policy
  - default-deny
home: https://kubernetes.io/docs/concepts/services-networking/network-policies/
sources:
  - https://github.com/ubiquitycluster/ubiquity
maintainers:
  - name: The Ubiquity Authors
    email: info@nousresearch.com