---
# Copyright The Ubiquity Authors.
#
# Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/ubiquitycluster/ubiquity/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# This software was previously licensed under the Functional Source License but has now transitioned to an Apache 2.0 License
# as of June 2025.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for network-policies.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Namespace to deploy the policies into
namespace: default

# -- Default-deny ingress policy settings
defaultDenyIngress:
  # -- Enable the default-deny ingress NetworkPolicy
  enabled: true

# -- Default-deny egress policy settings
defaultDenyEgress:
  # -- Enable the default-deny egress NetworkPolicy
  enabled: true

# -- Default-allow ingress policy settings (for namespace opt-out)
defaultAllowIngress:
  # -- Enable the default-allow ingress NetworkPolicy
  enabled: false

# -- Default-allow egress policy settings (for namespace opt-out)
defaultAllowEgress:
  # -- Enable the default-allow egress NetworkPolicy
  enabled: false

# -- Allow DNS egress policy settings
allowDns:
  # -- Enable the allow-dns egress NetworkPolicy
  enabled: true
  # -- The DNS service IP (use kube-dns or CoreDNS service name)
  dnsServiceName: kube-dns
  # -- The DNS namespace
  dnsNamespace: kube-system
  # -- The DNS port
  dnsPort: 53