#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/docs/reference/helm-charts.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

emit_chart_table() {
  local title="$1"
  shift
  echo "## $title"
  echo
  echo "| Path | Chart | Version | App version | Values | Tests |"
  echo "|------|-------|---------|-------------|--------|-------|"
  while IFS= read -r chart; do
    local dir name version app values tests
    dir="$(dirname "$chart")"
    name="$(sed -n 's/^name:[[:space:]]*//p' "$chart" | head -1 | tr -d '"')"
    version="$(sed -n 's/^version:[[:space:]]*//p' "$chart" | head -1 | tr -d '"')"
    app="$(sed -n 's/^appVersion:[[:space:]]*//p' "$chart" | head -1 | tr -d '"')"
    [[ -f "$dir/values.yaml" ]] && values="yes" || values="no"
    if compgen -G "$dir/tests/*.yaml" >/dev/null; then tests="yes"; else tests="no"; fi
    printf '| `%s` | `%s` | `%s` | `%s` | %s | %s |\n' "$dir" "${name:-unknown}" "${version:-unknown}" "${app:-n/a}" "$values" "$tests"
  done < <(find "$@" -name Chart.yaml -not -path '*/disabled/*' | sed "s#^$ROOT/##" | sort)
  echo
}

{
  echo "# Helm Chart Reference"
  echo
  echo "<!-- AUTO-GENERATED by scripts/generate-helm-chart-reference.sh; do not edit by hand. -->"
  echo
  echo 'This reference is generated from active `Chart.yaml`, `values.yaml`, and chart `tests/*.yaml` files. The generator scans `find system platform -name Chart.yaml` plus Kustomize roots under `platform/hpc-ubiq`. Run:'
  echo
  echo '```sh'
  echo "scripts/generate-helm-chart-reference.sh --check"
  echo '```'
  echo
  emit_chart_table "System charts" "$ROOT/system"
  emit_chart_table "Platform charts" "$ROOT/platform"
  echo "## Kustomize composition roots"
  echo
  echo 'Most system and platform components are packaged as Helm charts. Kustomize roots remain composition or workload-overlay boundaries, with `platform/hpc-ubiq` carrying legacy HPC/Slurm overlays that are documented in `docs/architecture/kustomize-helm.md`.'
  echo
  echo "| Path | Purpose |"
  echo "|------|---------|"
  while IFS= read -r kust; do
    dir="$(dirname "$kust")"
    printf '| `%s` | Kustomize overlay/composition root |\n' "$dir"
  done < <(find "$ROOT/platform/hpc-ubiq" -name kustomization.yaml | sed "s#^$ROOT/##" | sort)
} >"$TMP"

if [[ "${1:-}" == "--check" ]]; then
  if [[ ! -f "$OUT" ]] || ! cmp -s "$TMP" "$OUT"; then
    echo "docs/reference/helm-charts.md is out of date; run scripts/generate-helm-chart-reference.sh" >&2
    diff -u "$OUT" "$TMP" || true
    exit 1
  fi
  echo "docs/reference/helm-charts.md is current"
  exit 0
fi

cp "$TMP" "$OUT"
echo "wrote $OUT"
