#!/usr/bin/env python
# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Functional Source License, Version 1.0, Apache 2.0 Change License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity/blob/main/LICENSE.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# It also allows for the transition of this software to an Apache 2.0 Licence
# on the second anniversary of the date we make the software available.
# See the License for the specific language governing permissions and
# limitations under the License.

# WIP
# - [x] take screenshot
# - [ ] self contained
# - [ ] login automatically credentials from Kubernetes Secrets (is this really needed?)

# TODO put this in tools container or use Docker
# pip install selenium
# sudo pacman -S geckodriver

import time
from selenium import webdriver

apps = [
    {
        'name': 'home',
        'url': 'https://home.ubiquitycluster.uk'
    },
    {
        'name': 'gitea',
        'url': 'https://git.ubiquitycluster.uk/ops/ubiquity'
    },
    {
        'name': 'argocd',
        'url': 'https://argocd.ubiquitycluster.uk/applications/root'
    },
    {
        'name': 'vault',
        'url': 'https://vault.ubiquitycluster.uk/ui/vault/secrets'
    },
    {
        'name': 'tekton',
        'url': 'https://tekton.ubiquitycluster.uk/#/namespaces/tekton-pipelines/pipelineruns/ubiquity?pipelineTask=external&step=plan'
    },
    {
        'name': 'matrix',
        'url': 'https://chat.ubiquitycluster.uk/#/room/#random:matrix.ubiquitycluster.uk'
    },
    {
        'name': 'grafana',
        'url': 'https://grafana.ubiquitycluster.uk/d/efa86fd1d0c121a26444b636a3f509a8/kubernetes-compute-resources-cluster'  # wtf is this ID
    },
]

options = webdriver.firefox.options.Options()
options.headless = True

driver = webdriver.Firefox(
    options=options,
    firefox_profile=webdriver.FirefoxProfile(  # TODO deprecated
        profile_directory="/home/cjcshadowsan/.mozilla/firefox/h05irklw.default-release"  # TODO do not hard code
    )
)
driver.set_window_size(1920, 1080)

for app in apps:
    print(f"Opening {app['url']}")
    driver.get(app['url'])
    time.sleep(3)  # TODO wait for full page load instead of sleep
    driver.save_screenshot(f"{app['name']}.png")
    print(f"Screenshot saved to {app['name']}.png")

driver.close()
