#!/usr/bin/env python3.9
# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0. Previously licensed under the Functional Source License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity-open/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# This software was previously licensed under the Functional Source License but has now transitioned to an Apache 2.0 License
# as of June 2025.
# See the License for the specific language governing permissions and
# limitations under the License.

import requests

from kubernetes import client, config
from rich.console import Console
from time import sleep

# Essential services
ingresses = [
    {
        'name': 'argocd-server',
        'fullname': 'ArgoCD',
        'namespace': 'argocd'
    },
    {
        'name': 'hajimari',
        'fullname': 'Homepage',
        'namespace': 'hajimari'
    },
    {
        'name': 'vault',
        'fullname': 'Vault',
        'namespace': 'vault'
    },
    {
        'name': 'gitea',
        'fullname': 'Gitea',
        'namespace': 'gitea'
    },
]


def wait_app(name: str, fullname: str, namespace: str) -> None:
    console = Console()
    success = False

    with console.status(f"Waiting for {fullname}"):
        while not success:
            try:
                ingress = client.NetworkingV1Api().read_namespaced_ingress(
                    name,
                    namespace
                )
                url = f"https://{ingress.spec.rules[0].host}"
                requests.get(url, verify=False).raise_for_status()
                console.log(f"{fullname} is ready, visit {url}")
                success = True
            except Exception:
                #console.log(f"{fullname} not ready, ingress = {ingress.spec.rules[0].host}")
                sleep(30)


def main() -> None:
    Console().rule("Waiting for essential applications")
    config.load_kube_config(config_file='./metal/kubeconfig.yaml')
    requests.urllib3.disable_warnings()

    for ingress in ingresses:
        wait_app(ingress['name'], ingress['fullname'], ingress['namespace'])

    print("Ubiquity core services online. You can start running jobs right away!")


if __name__ == '__main__':
    main()
