ARG VERSION

# --------------------------------------------------------------------------------------------------
# Builder Image
# --------------------------------------------------------------------------------------------------
# See ./builder for this image
FROM localhost/opus-builder AS builder

# Required tools for building Python packages
RUN set -eux \
	&& dnf -y install \
		libpq-devel \
		libpq

# Python packages (copied to final image)
RUN set -eux \
	&& pip3 install --no-cache-dir --no-compile \
		PyMySQL \
		docker \
		jsondiff \
		netaddr \
		pexpect \
		psycopg2 \
		pymongo \
		pypsexec \
		smbprotocol \
	&& find /usr/lib/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
	&& find /usr/lib/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf \
	&& find /usr/local/lib/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
	&& find /usr/local/lib/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf \
	&& find /usr/local/lib64/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
	&& find /usr/local/lib64/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf \
	&& find /local/lib/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
	&& find /local/lib/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf	\
	&& find /local/lib64/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
	&& find /local/lib64/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf


# --------------------------------------------------------------------------------------------------
# Final Image
# --------------------------------------------------------------------------------------------------
FROM localhost/opus:${VERSION}-tools AS production
ARG VERSION
# https://github.com/opencontainers/image-spec/blob/master/annotations.md
#LABEL "org.opencontainers.image.created"=""
#LABEL "org.opencontainers.image.version"=""
#LABEL "org.opencontainers.image.revision"=""
LABEL "maintainer"="cjcshadowsan <christopher.james.coates@gmail.com>"
LABEL "org.opencontainers.image.authors"="cjcshadowsan <christopher.james.coates@gmail.com>"
LABEL "org.opencontainers.image.vendor"="cjcshadowsan"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.url"="https://github.com/cjcshadowsan/opus-seed"
LABEL "org.opencontainers.image.documentation"="https://github.com/cjcshadowsan/opus-seed"
LABEL "org.opencontainers.image.source"="https://github.com/cjcshadowsan/opus-seed"
LABEL "org.opencontainers.image.ref.name"="Ansible ${VERSION} infra"
LABEL "org.opencontainers.image.title"="Ansible ${VERSION} infra"
LABEL "org.opencontainers.image.description"="Ansible ${VERSION} infra"

# Additional binaries
RUN set -eux \
	&& dnf -y install \
		libpq \
		rsync

COPY --from=builder /usr/local/lib/python3.12/ /usr/local/lib/python3.12/

WORKDIR /data
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/bash"]
