apiVersion: v1
kind: Pod
metadata:
  name: missing-label-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
