apiVersion: v1
kind: Pod
metadata:
  name: valid-pod
  labels:
    app.kubernetes.io/name: valid-pod
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      runAsNonRoot: true
      privileged: false
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    resources:
      limits:
        memory: 256Mi
        cpu: 500m
